### ISSUE TITLE
missing argument check in check_sophos_xg_vpn.pl

### ISSUE THREAD

**Issue by Terminator81** [DinoTools/monitoring-check_sophos_xg#16]
the name of the Tunnel must be set to check the state of the tunnel

$mp->add_arg(
    spec    => 'name=s',
    help    => 'Name of the VPN tunnel',
    required => 1,
);

**Comment by phibos** [comment]
Thanks for your work, but the VPN plugin is broken because we get wrong or unexpected values from the device. If this issue can be fixed we can readd the plugin and also fix this issue.
