### ISSUE TITLE
sophos xg nagios Plugin for Cpu and bandwidth

### ISSUE THREAD

**Issue by kumars2570** [DinoTools/monitoring-check_sophos_xg#18]
fo sophos xg:  nagios Plugin for Cpu and bandwidth monitor ?
Require if anyone have please share
thanks

**Comment by phibos** [comment]
Sophos XG uses the standardized OIDs for load and network interfaces.

- For the load you can use the Manubulon check_snmp_load.pl plugin. https://github.com/SteScho/manubulon-snmp
- For the network interfaces you can use check_netint.pl from our fork https://github.com/DinoTools/monitoring-check_netint or from an other location in the internet.

Also Icinga Exchange, Nagios Exchange or github might be some good places to look for generic monitoring plugins.
