### ISSUE TITLE
To install sophos plugins

### ISSUE THREAD

**Issue by manishfaith82** [DinoTools/monitoring-check_sophos_xg#9]
Hi Team.
I am using the CheckMK raw edition. It is fantastic and wonderful tool to monitor network resources.
I am using the Sophos xg Firewall v19. I wanted to monitor Sophos services. However, when I added it through SNMP, It checks, but some services are not displayed. When I googled and found this link of plugins for Nagios: [GitHub - DinoTools/monitoring-check_sophos_xg: Monitoring plugin to check Sophos XG firewalls with Icinga, Nagios and other compatible monitoring solutions](https://github.com/DinoTools/monitoring-check_sophos_xg#readme)
I want to install Sophos Nagios plugins in CheckMK. Can you please help?

Operating system: Ubuntu 22.04
Checkmk Version: OMD - Open Monitoring Distribution Version 2.1.0p24.cre

**Comment by manishfaith82** [comment]
While installing **check_sophos_xg_vpn.pl** I have got error. I have successfully install other sophos plugins.

**OMD[monitoring]:~/local/lib/nagios/plugins$ ./check_sophos_xg_vpn.pl -H 10.100.26.1
Use of uninitialized value in string eq at ./check_sophos_xg_vpn.pl line 126.**

Can you pls help me

**Comment by phibos** [comment]
Sadly the vpn check does not work as expected. I have used the check with different firewalls and did a snmpwalk but at the moment it is not possible to say if a vpn connection is up or down. On some firewalls some OIDs are missing and some other values report different stats as documented.

**Comment by phibos** [comment]
Sadly no response closing the issue.
